name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: macOS-10.15

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        path: plugins
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        path: flutter
        repository: flutter/flutter
        ref: master
        # Shallow clones don't work; see https://github.com/flutter/flutter/issues/18532
        fetch-depth: 0
    - name: Add Flutter tags
      # Add tags, which are also necessary for version checks to work.
      run: git fetch origin +refs/tags/*:refs/tags/*
      working-directory: ${{ github.workspace }}/flutter
    - name: Add Flutter to path
      run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
    - name: Enable macOS support
      run: flutter config --enable-macos-desktop
    - name: Doctor
      # Run doctor, for ease of debugging any issues.
      run: flutter doctor -v
    - name: Build all_plugins app
      run: ./script/build_all_plugins_app.sh macos
      working-directory: ${{ github.workspace }}/plugins
    - name: Drive examples
      run: |
        ./script/incremental_build.sh build-examples --macos --no-ipa
        ./script/incremental_build.sh drive-examples --macos
      working-directory: ${{ github.workspace }}/plugins
